# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

ifeq ($(config),debug)
TARGETDIR = bin/debug
TARGET = $(TARGETDIR)/SeqPhase
  define BUILDCMDS
	@echo Running build commands
	cd SeqPHASE/haxe; haxe --cpp ../cpp -D static_link SeqPhase1.hx SeqPhase2.hx
	cp SeqPHASE/cpp/liboutput.a build/bin/debug/libseqphase.a
  endef
  define CLEANCMDS
  endef

else ifeq ($(config),release)
TARGETDIR = bin/release
TARGET = $(TARGETDIR)/SeqPhase
  define BUILDCMDS
	@echo Running build commands
	cd SeqPHASE/haxe; haxe --cpp ../cpp -D static_link SeqPhase1.hx SeqPhase2.hx
	cp SeqPHASE/cpp/liboutput.a build/bin/debug/libseqphase.a
  endef
  define CLEANCMDS
  endef

else
  $(error "invalid configuration $(config)")
endif

$(TARGET):
	$(BUILDCMDS)

clean:
	$(CLEANCMDS)
