name: Tests

on:
  push:
    branches:
      - master

jobs:
  test-latest:
    name: Test latest on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up haxe
        uses: ./.github/actions/setup-haxe

      - name: Set up latest Python
        uses: ./.github/actions/python-latest

      - name: Lint with pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Test with pytest
        run: |
          pip install pytest
          pytest


  test-frozen:
    name: Test frozen on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up haxe
        uses: ./.github/actions/setup-haxe

      - name: Set up test Python
        uses: ./.github/actions/python-test

      - name: Lint with pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Test with pytest
        run: |
          pip install pytest
          pytest
