name: Deploy

on: push

jobs:

  build-wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.2

      - name: Install hxcpp
        run: |
          haxe -version
          haxelib install hxcpp

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BUILD_VERBOSITY: 3
          CIBW_BEFORE_BUILD_LINUX: >
            yum update &&
            yum install haxe-4.3.2-1 -y &&
            mkdir ~/haxelib &&
            haxelib setup ~/haxelib &&
            haxelib install hxcpp 4.3.2
          CIBW_BEFORE_TEST: >
            pip install -r requirements.txt &&
            pip install -i https://test.pypi.org/simple/ -r requirements-testpypi.txt
          CIBW_SKIP: "pp* *-win32"
          CIBW_ARCHS_MACOS: x86_64 arm64

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: ./wheelhouse/*.whl


  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/*.tar.gz
